# Example configuration for P1 Reader Home Assistant Custom Component
# Add this to your configuration.yaml file

# Basic configuration
sensor:
  - platform: p1_reader
    host: zap.local
    
# Advanced configuration with all options
# sensor:
#   - platform: p1_reader
#     host: 192.168.1.100  # IP address or hostname of your Zap device
#     endpoint: /api/data/p1/obis  # P1 data API endpoint (default)
#     system_endpoint: /api/system  # System info API endpoint (default)
#     name: Zap  # Custom name prefix for sensors (default)
#     scan_interval: 10  # Update interval in seconds (default: 10)

# Optional: Enable debug logging
logger:
  logs:
    custom_components.p1_reader: debug

# Optional: Energy dashboard configuration
# Once the integration is running, you can add these sensors to your energy dashboard:
# - Grid consumption: sensor.zap_total_energy_import
# - Return to grid: sensor.zap_total_energy_export
# - Net power: sensor.zap_net_power (useful for automation)

# Example automation using the Zap sensors
automation:
  - alias: "High Power Usage Alert"
    trigger:
      - platform: numeric_state
        entity_id: sensor.zap_net_power
        above: 3.0  # Alert when consuming more than 3kW
    action:
      - service: notify.mobile_app_your_phone
        data:
          message: "High power usage detected: {{ states('sensor.zap_net_power') }} kW"
          title: "Energy Alert"
  
  - alias: "Solar Export Notification"
    trigger:
      - platform: numeric_state
        entity_id: sensor.zap_net_power
        below: -1.0  # Alert when exporting more than 1kW
    action:
      - service: notify.mobile_app_your_phone
        data:
          message: "Solar panels are exporting: {{ states('sensor.zap_net_power')|abs }} kW"
          title: "Solar Export" 