name: Validate Sourceful Energy Zap Component

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install homeassistant
        pip install black flake8 pylint mypy
    
    - name: Check code formatting with black
      run: |
        black --check --diff custom_components/
    
    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 custom_components/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 custom_components/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Lint with pylint
      run: |
        pylint custom_components/sourceful_zap/ || true
    
    - name: Type checking with mypy
      run: |
        mypy custom_components/sourceful_zap/ || true
    
    - name: Validate manifest.json
      run: |
        python -m json.tool custom_components/sourceful_zap/manifest.json > /dev/null
        echo "manifest.json is valid JSON"
    
    - name: Check required files exist
      run: |
        test -f custom_components/sourceful_zap/manifest.json || (echo "manifest.json missing" && exit 1)
        test -f custom_components/sourceful_zap/__init__.py || (echo "__init__.py missing" && exit 1)
        test -f custom_components/sourceful_zap/sensor.py || (echo "sensor.py missing" && exit 1)
        echo "All required files exist"
    
    - name: Check HACS requirements
      run: |
        test -f hacs.json || (echo "hacs.json missing" && exit 1)
        python -m json.tool hacs.json > /dev/null
        echo "HACS configuration is valid"
    
    - name: Check branding files
      run: |
        test -f icon.png || (echo "icon.png missing" && exit 1)
        echo "Integration icon exists"
    
    - name: Validate Python imports
      run: |
        python -c "
        import sys
        sys.path.insert(0, 'custom_components/sourceful_zap')
        try:
            import sensor
            print('sensor.py imports successfully')
        except Exception as e:
            print(f'Import error: {e}')
            sys.exit(1)
        "

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install security tools
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety
    
    - name: Run security check with bandit
      run: |
        bandit -r custom_components/ -f json || true
    
    - name: Check for known security vulnerabilities
      run: |
        safety check || true 